[package]
name = "rust-packet-logger"
version = "0.1.0"
edition = "2021"


[dependencies]
pnet = "0.34.0"
clap = { version = "4.5.4", features = ["derive"] }
chrono = "0.4"
colored = "2.1"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"


[dev-dependencies]
# For tests
pnet = "0.34.0"


